Repository universal-ember/ember-primitives, pull requests merged in 2024-02, with the labels that each got.

#231 Upgrade lint deps
  dev/package.json
  docs-app/package.json
  ember-primitives/package.json
  package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: internal

#233 Upgrade types-related dependencies
  dev/package.json
  docs-api/package.json
  docs-app/package.json
  ember-primitives/package.json
  package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: internal

#235 fix prepack command so types are shipped
  ember-primitives/package.json
Labels: bug

#239 [OTP Input]: add better correction behavior when using both mouse and keyboard
  ember-primitives/src/components/one-time-password/input.gts
  ember-primitives/src/components/one-time-password/utils.ts
  test-app/tests/one-time-password/otp-input-rendering-test.gts
Labels: bug, enhancement

#240 [OTP]: Resolve pasting and focus state issues
  ember-primitives/src/components/one-time-password/input.gts
  ember-primitives/src/components/one-time-password/utils.ts
  test-app/tests/one-time-password/otp-input-rendering-test.gts
Labels: bug

#241 [OTP]: Disable autocomplete on the input fields
  ember-primitives/src/components/one-time-password/input.gts
Labels: enhancement

#242 [Avatar] Fix flaky test
  test-app/tests/avatar/rendering-test.gts
Labels: internal

#243 [OTP]: Fix issue with backspace repeating faster than the otp input logic could keep up with (by keeping up with it)
  ember-primitives/src/components/one-time-password/input.gts
  ember-primitives/src/components/one-time-password/utils.ts
  ember-primitives/src/test-support/otp.ts
  test-app/tests/one-time-password/otp-input-rendering-test.gts
Labels: bug

#244 [Docs]: Explain how body-lock works with <Modal>
  docs-app/public/docs/5-floaty-bits/modal.md
Labels: documentation

#246 Unify with the v2 addon blueprint, using extensions in the imports and stuch
  .prettierignore
  ember-primitives/.eslintignore
  ember-primitives/.gitignore
  ember-primitives/.prettierignore
  ember-primitives/babel.config.cjs
  ember-primitives/package.json
  ember-primitives/rollup.config.mjs
  ember-primitives/src/components/accordion.gts
  ember-primitives/src/components/accordion/content.gts
  ember-primitives/src/components/accordion/header.gts
  ember-primitives/src/components/accordion/item.gts
  ember-primitives/src/components/accordion/public.ts
  ember-primitives/src/components/accordion/trigger.gts
  ember-primitives/src/components/link.gts
  ember-primitives/src/components/one-time-password/index.gts
  ember-primitives/src/components/one-time-password/input.gts
  ember-primitives/src/components/one-time-password/otp.gts
  ember-primitives/src/components/popover.gts
  ember-primitives/src/components/portal.gts
  ember-primitives/src/components/switch.gts
  ember-primitives/src/components/toggle.gts
  ember-primitives/src/helpers.ts
  ember-primitives/src/index.ts
  ember-primitives/src/test-support/index.ts
  ember-primitives/src/test-support/routing.ts
  ember-primitives/tsconfig.json
  ember-primitives/tsconfig.typedoc.json
  pnpm-lock.yaml
  test-app/.prettierignore
Labels: internal

#248 [OTP] Trigger an input event for backspace
  ember-primitives/src/components/one-time-password/utils.ts
Labels: bug

#255 [OTP] makes backspace stay in current input unless it's empty
  ember-primitives/src/components/one-time-password/utils.ts
Labels: bug
