Repository universal-ember/ember-primitives, pull requests merged in 2024-10, with the labels that each got.

#370 Update release-plan
  .github/workflows/plan-release.yml
  .github/workflows/publish.yml
  RELEASE.md
  package.json
Labels: internal

#372 Upgrade tabster
  ember-primitives/package.json
  ember-primitives/src/components/menu.gts
  ember-primitives/src/components/toggle-group.gts
  pnpm-lock.yaml
Labels: enhancement

#380 [Breaking] Document and solidify the public API of FloatingUI
  docs-app/app/components/nav.gts
  docs-app/app/routes/api-docs.gts
  docs-app/app/routes/application.ts
  docs-app/public/docs/5-floaty-bits/floating-ui.md
  docs-app/public/docs/5-floaty-bits/popover.md
  docs-app/public/docs/6-utils/data-from-event.json
  docs-app/public/docs/6-utils/should-handle-link.json
  ember-primitives/src/components/menu.gts
  ember-primitives/src/components/popover.gts
  ember-primitives/src/floating-ui.ts
  ember-primitives/src/floating-ui/component.gts
  ember-primitives/src/floating-ui/middleware.ts
  ember-primitives/src/floating-ui/modifier.ts
  test-app/tests/floating-ui/component-main-test.gts
  test-app/tests/floating-ui/component-test.gts
  test-app/tests/floating-ui/modifier-test.gts
Labels: enhancement

#383 add stopPropagation arg to menu trigger
  ember-primitives/src/components/menu.gts
  test-app/tests/menu/menu-rendering-test.gts
Labels: enhancement

#382 Upgrade dev deps
  .github/workflows/ci.yml
  dev/package.json
  docs-app/app/router.ts
  docs-app/package.json
  ember-primitives/package.json
  ember-primitives/rollup.config.mjs
  ember-primitives/src/components/accordion/content.gts
  ember-primitives/src/components/accordion/header.gts
  ember-primitives/src/components/accordion/public.ts
  ember-primitives/src/components/accordion/trigger.gts
  ember-primitives/src/components/menu.gts
  ember-primitives/src/components/portal-targets.gts
  ember-primitives/src/proper-links.ts
  ember-primitives/unpublished-development-types/index.d.ts
  package.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
  test-app/package.json
  turbo.json
Labels: internal

#384 Upgrade more devdeps
  dev/package.json
  docs-app/package.json
  ember-primitives/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: internal

#385 add preventDefault arg to menu trigger
  ember-primitives/src/components/menu.gts
  test-app/tests/menu/menu-rendering-test.gts
Labels: enhancement

#388 Update index.gts
  docs-app/app/templates/index.gts
Labels: documentation
